# Generated by Django 3.2b1 on 2021-03-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_name_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
